### ISSUE TITLE
Add AuthGard Providers in app module and remove add global Gaurds with useGlobalGaurds

### ISSUE THREAD

**Issue by gnlscience** [TrejGun/graphql-based-authorization-for-nestjs#271]
Thanks for your example. It helped me alot

https://github.com/TrejGun/graphql-based-authorization-for-nestjs/blob/97cf14eb4b6417c40b8150f57a123137f465d5a5/src/index.ts#L15

You can do this without this awkward Reflector dependency injection 
https://docs.nestjs.com/guards#binding-guards

**Comment by TrejGun** [comment]
yes you are right this will work too

I dont know what I like less tho
```
  const reflector = app.get(Reflector);
  app.useGlobalGuards(new JwtGuard(reflector));
  app.useGlobalGuards(new RolesGuard(reflector));
```
or
```
@Module({
  providers: [
    {
      provide: APP_GUARD,
      useClass: JwtGuard,
    },
    {
      provide: APP_GUARD,
      useClass: RolesGuard,
    },
  ],
```
for now i will keep it as it is because i'm just lazy to fix this in 4 repos

**Comment by TrejGun** [comment]
@gnlscience fixed :)
